# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22b8cc3e38c283dc3a595fa8b7b927c4cb4462d1ff2cc8ebb2b03c0d2f06e23e0b594713c0da75dfaadb5f7b5072f5245f9545928ddca4f207a621c238f2f5d5

test:
  secret_key_base: 01622e8b7430b853aee53c80171627d2562433aac7373e1cf618611d9e4df7c4b71737d7526730818379518b4c3e75f2b348093027bf39af2f48ef6f355c35b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
